---
title: "Trabajo Maestría"
author: "Melina D'Alessandro"
date: "7/25/2020"
output: html_document
---

```{r}
library(tidyverse)
```

# INPUT
```{r input, include=FALSE}
drug <- read.csv("input/faers_ascii_2020Q1/ascii/DRUG20Q1.txt", sep = "$", stringsAsFactors = FALSE)
reac <- read.csv("input/faers_ascii_2020Q1/ascii/REAC20Q1.txt", sep = "$", stringsAsFactors = FALSE)
```

```{r}
drug_reac <- left_join(drug, reac, by = c("primaryid", "caseid"))

drug_reac <- drug_reac %>% 
  filter(prod_ai != "" & prod_ai != "COSMETICS") %>% 
  group_by(prod_ai, pt) %>% 
  tally()

#head(drug_reac %>% arrange(desc(n)))
```
```{r}
#ggplot(drug_reac) +
#  geom_boxplot(aes(y = n))
```

```{r}
# Busco los valores que son outliers definidos como (Q3 + 1.5x IQR)

q3 <- quantile(drug_reac$n, 0.75)
q1 <- quantile(drug_reac$n, 0.25)
iqr <- (q3 - q1)
lim_outlier <- (q3 + (1.5 * iqr))

```

```{r}
drug_reac_filtered <- drug_reac %>% 
  filter(n < lim_outlier)
```

```{r}
# Para un producto en particular
#tabla <- drug_reac %>% 
#  ungroup(prod_ai) %>% 
#  mutate(pt = ifelse(pt == "Condition aggravated", "condition", "other_condition"),
#         prod_ai = ifelse(prod_ai == "INFLIXIMAB-DYYB", "product", "other_product"))
#
#tabla <- tabla %>% 
#  group_by(pt, prod_ai) %>% 
#  summarise(n = sum(n)) %>% 
#  pivot_wider(., names_from = pt, values_from = n) %>% 
#  arrange(desc(prod_ai))
#  
#tabla <- tabla %>% 
#  mutate(total_prod = rowSums(tabla[,2:3], na.rm=TRUE))
#
#valor_ppr <- (tabla[1,2] / tabla[1,4]) / (tabla[2,2] / tabla[2,4])
#
#lista <- tibble(producto = "INFLIXIMAB-DYYB", condition = "Condition aggravated", ppr = valor_ppr[1,1])

```

```{r}
# Funcion para calcular el valor para todos los productos que tienen mucha cantidad de reportes

calc_ppr <- function(product, condition) {
  
  tabla <- drug_reac %>% 
  ungroup(prod_ai) %>% 
  mutate(pt = ifelse(pt == condition, "condition", "other_condition"),
         prod_ai = ifelse(prod_ai == product, "product", "other_product"))
  
  tabla <- tabla %>% 
    group_by(pt, prod_ai) %>% 
    summarise(n = sum(n)) %>% 
    pivot_wider(., names_from = pt, values_from = n) %>% 
    arrange(desc(prod_ai))
    
  tabla <- tabla %>% 
    mutate(total_prod = rowSums(tabla[,2:3], na.rm=TRUE))
  
  valor_ppr <- (tabla[1,2] / tabla[1,4]) / (tabla[2,2] / tabla[2,4])
  
  lista <- tibble(product = product, condition = condition, ppr = valor_ppr[1,1])
  
  return(lista)

}

```

```{r}
# Se calcula el prr para las combinaciones droga-evento
lista_resultados1 <- tibble()

system.time(
for (i in 1:nrow(drug_reac_filtered)) {
  product = drug_reac_filtered[i, 1] %>% pull() %>% as.character()
  condition = drug_reac_filtered[i, 2] %>% pull() %>% as.character()
  tmp_df <- calc_ppr(product, condition)
  lista_resultados1 <- bind_rows(lista_resultados1, tmp_df)
}
)

write.csv(lista_resultados, "output/lista_resultados_menor_1.csv", row.names = FALSE)
```

```{r}
# Se filtran los valores de prr >=1 para hacer el análisis
#lista_resultados_filtrada <- lista_resultados %>% 
#  filter(ppr >= 1) 
#
#drug_reac_filtered <- drug_reac_filtered %>% 
#  ungroup(prod_ai) %>% 
#  mutate(prod_ai = as.character(prod_ai),
#         pt = as.character(pt))

```

# Se genera el dataset de producto-evento con todas las variables

```{r}
lista_resultados <- read.csv("output/lista_resultados.csv", stringsAsFactors = FALSE)
```

```{r}
demo <- read.csv("input/faers_ascii_2020Q1/ascii/DEMO20Q1.txt", sep = "$", stringsAsFactors = FALSE)
indi <- read.csv("input/faers_ascii_2020Q1/ascii/INDI20Q1.txt", sep = "$", stringsAsFactors = FALSE)
outc <- read.csv("input/faers_ascii_2020Q1/ascii/OUTC20Q1.txt", sep = "$", stringsAsFactors = FALSE)
ther <- read.csv("input/faers_ascii_2020Q1/ascii/THER20Q1.txt", sep = "$", stringsAsFactors = FALSE)
rpsr <- read.csv("input/faers_ascii_2020Q1/ascii/RPSR20Q1.txt", sep = "$", stringsAsFactors = FALSE)

```

```{r}
#drug_reac <- drug_reac %>% 
#  ungroup(prod_ai) %>% 
#  mutate(prod_ai = as.character(prod_ai),
#         pt = as.character(pt))
#
#datos <- left_join(drug_reac, drug_reac_filtered, by = c("prod_ai", "pt"))
```

# DEMO

```{r} 
# wt_cod es la variable de medicion de la variable de peso utilizada, paso todos los valores a kg
summary(as.factor(demo$age_cod))

str(demo1)

demo <- demo %>% 
  mutate(wt = ifelse(wt_cod != "LBS", wt, 0.453592 * wt),
         age = as.numeric(age),
         age = case_when(age_cod == "DEC" ~ age * 10,
                         age_cod == "DY" ~ age / 365,
                         age_cod == "HR" ~ age / (24 * 365),
                         age_cod == "MON" ~ age / 12,
                         age_cod == "WK" ~ age / 52,
                         TRUE ~ age))

#  select(-caseversion, i_f_code, wt_cod, -age_cod, e_sub)

```
# Union de los datasets con variables limpias

```{r}
datos <- left_join(drug, reac, by = c("primaryid", "caseid")) %>% 
  left_join(lista_resultados, by = c("prod_ai" = "product",
                                     "pt" = "condition"))

datos <- datos %>% 
  filter(!is.na(ppr))

datos <- datos %>% 
  left_join(., outc, by = c("primaryid", "caseid")) %>% 
  left_join(., demo, by = c("primaryid", "caseid")) #%>% 
 # left_join(., ther, by = c("primaryid", "caseid"))

colnames(datos)
```

